GET http://localhost:3001/api/persons
###
#GET http://localhost:3001/api/persons/686286009d1d9d3545447ded
GET http://localhost:3001/api/persons/a
###
DELETE http://localhost:3001/api/persons/3
###
POST http://localhost:3001/api/persons 
Content-Type: application/json

{
    "name": "Neon Noodle", 
    "number": "215-840-3475"
}